### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by hopewise** [onkel-dirtus/logger_file_backend#31]
I tried to use it, but I got this error:

```
=INFO REPORT==== 15-Feb-2017::17:19:34 ===
    application: logger
    exited: {{shutdown,
              {failed_to_start_child,'Elixir.Logger.Watcher',
               {'EXIT',
                {{badmatch,
                  {error,
                   {{{case_clause,
                      {'EXIT',
                       {undef,
                        [{'Elixir.LoggerFileBackend',init,
                          [{'Elixir.LoggerFileBackend',error_log}],
                          []},
                         {gen_event,server_add_handler,4,
                          [{file,"gen_event.erl"},{line,429}]},
                         {gen_event,handle_msg,5,
                          [{file,"gen_event.erl"},{line,274}]},
                         {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}}},
                     [{'Elixir.Logger.Watcher',do_init,3,
                       [{file,"lib/logger/watcher.ex"},{line,78}]},
                      {gen_server,init_it,6,
                       [{file,"gen_server.erl"},{line,328}]},
                      {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]},
                    {child,undefined,
                     {'Elixir.Logger.Watcher',
                      {'Elixir.Logger',
                       {'Elixir.LoggerFileBackend',error_log}}},
                     {'Elixir.Logger.Watcher',watcher,
                      ['Elixir.Logger',
                       {'Elixir.LoggerFileBackend',error_log},
                       {'Elixir.LoggerFileBackend',error_log}]},
                     transient,5000,worker,
                     ['Elixir.Logger.Watcher']}}}},
                 [{'Elixir.Logger.Watcher','-start_link/3-fun-0-',2,
                   [{file,"lib/logger/watcher.ex"},{line,16}]},
                  {'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,
                   [{file,"lib/enum.ex"},{line,1755}]},
                  {'Elixir.Logger.Watcher',start_link,3,
                   [{file,"lib/logger/watcher.ex"},{line,15}]},
                  {supervisor,do_start_child,2,
                   [{file,"supervisor.erl"},{line,365}]},
                  {supervisor,start_children,3,
                   [{file,"supervisor.erl"},{line,348}]},
                  {supervisor,init_children,2,
                   [{file,"supervisor.erl"},{line,314}]},
                  {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
                  {proc_lib,init_p_do_apply,3,
                   [{file,"proc_lib.erl"},{line,247}]}]}}}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary
** (Mix) Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: Logger.Watcher
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {{{:case_clause, {:EXIT, {:undef, [{LoggerFileBackend, :init, [{LoggerFileBackend, :error_log}], []}, {:gen_event, :server_add_handler, 4, [file: 'gen_event.erl', line: 429]}, {:gen_event, :handle_msg, 5, [file: 'gen_event.erl', line: 274]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}, [{Logger.Watcher, :do_init, 3, [file: 'lib/logger/watcher.ex', line: 78]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {:child, :undefined, {Logger.Watcher, {Logger, {LoggerFileBackend, :error_log}}}, {Logger.Watcher, :watcher, [Logger, {LoggerFileBackend, :error_log}, {LoggerFileBackend, :error_log}]}, :transient, 5000, :worker, [Logger.Watcher]}}}
            (logger) lib/logger/watcher.ex:16: anonymous fn/2 in Logger.Watcher.start_link/3
            (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
            (logger) lib/logger/watcher.ex:15: Logger.Watcher.start_link/3
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

```

any idea?

here is my config:

> 
> config :logger,
>   backends: [{LoggerFileBackend, :error_log}]
> 
> # configuration for the {LoggerFileBackend, :error_log} backend
> config :logger, :error_log,
>   path: "/var/log/myapp/phoenix_error.log",
>   level: :debug

**Comment by hopewise** [comment]
sorry, it was my mistake

**Comment by sztosz** [comment]
@hopewise Can you share what was your mistake? I'm having similar problem, and can't wrap my head around this for over an hour :/

**Comment by sztosz** [comment]
OK, if anyone is curious and have similar problem. Don't forget to add `{:logger_file_backend, "~> 0.0.9"}` to jour deps in `mix.exs` 
I forgot, silly me 🤣  but now it works like a charm!
@onkel-dirtus I strongly urge you to add need of having it in deps in mix.esx to readme :) So silly people like me will not forget about this :)

**Comment by digitsu** [comment]
does it have to be in all deps in mix.exs if using an umbrella project?  Or just at the top level?
